// Emoji dataset for the Google-Chat-style picker. Each item is { e, k }:
// e = the emoji, k = space-separated search keywords (lowercase).
// Tab icons are Material Symbols ligatures.

export const EMOJI_CATEGORIES = [
  {
    id: 'smileys', icon: 'mood', label: 'Smileys and emotions',
    emojis: [
      { e: '😀', k: 'grin smile happy' }, { e: '😃', k: 'smile happy joy' }, { e: '😄', k: 'smile happy laugh' },
      { e: '😁', k: 'grin beam happy' }, { e: '😆', k: 'laugh haha grin' }, { e: '😅', k: 'sweat laugh nervous' },
      { e: '😂', k: 'joy laugh tears cry' }, { e: '🤣', k: 'rofl rolling laugh' }, { e: '😊', k: 'blush smile shy' },
      { e: '😇', k: 'angel halo innocent' }, { e: '🙂', k: 'slight smile' }, { e: '🙃', k: 'upside down silly' },
      { e: '😉', k: 'wink flirt' }, { e: '😌', k: 'relieved calm' }, { e: '😍', k: 'love heart eyes' },
      { e: '🥰', k: 'love hearts adore' }, { e: '😘', k: 'kiss blow love' }, { e: '😗', k: 'kiss' },
      { e: '😋', k: 'yum tongue tasty' }, { e: '😛', k: 'tongue playful' }, { e: '😝', k: 'tongue silly' },
      { e: '😜', k: 'wink tongue crazy' }, { e: '🤪', k: 'zany goofy wild' }, { e: '🤨', k: 'raised eyebrow skeptic' },
      { e: '🧐', k: 'monocle thinking inspect' }, { e: '🤓', k: 'nerd glasses geek' }, { e: '😎', k: 'cool sunglasses' },
      { e: '🥳', k: 'party celebrate hat' }, { e: '😏', k: 'smirk sly' }, { e: '😒', k: 'unamused meh' },
      { e: '😞', k: 'sad disappointed' }, { e: '😔', k: 'pensive sad' }, { e: '😟', k: 'worried' },
      { e: '🙁', k: 'frown sad slight' }, { e: '😣', k: 'persevere struggle' }, { e: '😖', k: 'confounded' },
      { e: '😫', k: 'tired weary' }, { e: '😩', k: 'weary tired' }, { e: '🥺', k: 'pleading puppy beg' },
      { e: '😢', k: 'cry sad tear' }, { e: '😭', k: 'sob cry bawl' }, { e: '😤', k: 'huff triumph steam' },
      { e: '😠', k: 'angry mad' }, { e: '😡', k: 'rage furious mad' }, { e: '🤬', k: 'swear curse angry' },
      { e: '🤯', k: 'mind blown shock' }, { e: '😳', k: 'flushed embarrassed' }, { e: '🥵', k: 'hot heat sweat' },
      { e: '🥶', k: 'cold freeze' }, { e: '😱', k: 'scream fear shock' }, { e: '😨', k: 'fear scared' },
      { e: '😰', k: 'anxious sweat' }, { e: '🤗', k: 'hug hands' }, { e: '🤔', k: 'thinking hmm' },
      { e: '🤭', k: 'giggle oops hand' }, { e: '🤫', k: 'shush quiet secret' }, { e: '😶', k: 'no mouth blank' },
      { e: '😐', k: 'neutral meh' }, { e: '😑', k: 'expressionless' }, { e: '😬', k: 'grimace awkward' },
      { e: '🙄', k: 'eye roll annoyed' }, { e: '😮', k: 'wow surprise open' }, { e: '😲', k: 'astonished shock' },
      { e: '🥱', k: 'yawn tired bored' }, { e: '😴', k: 'sleep zzz' }, { e: '🤤', k: 'drool' },
      { e: '😷', k: 'mask sick' }, { e: '🤒', k: 'sick thermometer' }, { e: '🤮', k: 'vomit sick' },
      { e: '🥴', k: 'woozy drunk dizzy' }, { e: '😵', k: 'dizzy dead' }, { e: '🤐', k: 'zip mouth quiet' },
    ],
  },
  {
    id: 'people', icon: 'waving_hand', label: 'People and body',
    emojis: [
      { e: '👋', k: 'wave hello hi bye' }, { e: '🤚', k: 'raised back hand' }, { e: '✋', k: 'hand stop high five' },
      { e: '🖖', k: 'vulcan spock' }, { e: '👌', k: 'ok perfect' }, { e: '🤌', k: 'pinch italian' },
      { e: '🤏', k: 'pinch small tiny' }, { e: '✌️', k: 'peace victory' }, { e: '🤞', k: 'fingers crossed luck' },
      { e: '🫰', k: 'finger heart money' }, { e: '🤟', k: 'love you' }, { e: '🤘', k: 'rock horns' },
      { e: '🤙', k: 'call me shaka' }, { e: '👈', k: 'point left' }, { e: '👉', k: 'point right' },
      { e: '👆', k: 'point up' }, { e: '👇', k: 'point down' }, { e: '☝️', k: 'point up index' },
      { e: '👍', k: 'thumbs up like yes' }, { e: '👎', k: 'thumbs down no dislike' }, { e: '✊', k: 'fist raised' },
      { e: '👊', k: 'fist bump punch' }, { e: '🤛', k: 'fist left' }, { e: '🤜', k: 'fist right' },
      { e: '👏', k: 'clap applause' }, { e: '🙌', k: 'raise hands praise hooray' }, { e: '👐', k: 'open hands' },
      { e: '🤲', k: 'palms up pray' }, { e: '🤝', k: 'handshake deal' }, { e: '🙏', k: 'pray thanks please' },
      { e: '✍️', k: 'write hand' }, { e: '💅', k: 'nails sassy' }, { e: '🤳', k: 'selfie' },
      { e: '💪', k: 'muscle strong flex' }, { e: '🦾', k: 'mechanical arm robot' }, { e: '👀', k: 'eyes look' },
      { e: '👁️', k: 'eye' }, { e: '👅', k: 'tongue' }, { e: '👄', k: 'lips mouth' }, { e: '💋', k: 'kiss lips' },
      { e: '🧠', k: 'brain smart' }, { e: '👶', k: 'baby' }, { e: '🧑', k: 'person' }, { e: '👨', k: 'man' },
      { e: '👩', k: 'woman' }, { e: '🧔', k: 'beard' }, { e: '👮', k: 'police cop' }, { e: '🕵️', k: 'detective spy' },
    ],
  },
  {
    id: 'nature', icon: 'pets', label: 'Animals and nature',
    emojis: [
      { e: '🐶', k: 'dog puppy' }, { e: '🐱', k: 'cat kitten' }, { e: '🐭', k: 'mouse' }, { e: '🐹', k: 'hamster' },
      { e: '🐰', k: 'rabbit bunny' }, { e: '🦊', k: 'fox' }, { e: '🐻', k: 'bear' }, { e: '🐼', k: 'panda' },
      { e: '🐨', k: 'koala' }, { e: '🐯', k: 'tiger' }, { e: '🦁', k: 'lion' }, { e: '🐮', k: 'cow' },
      { e: '🐷', k: 'pig' }, { e: '🐸', k: 'frog' }, { e: '🐵', k: 'monkey' }, { e: '🐔', k: 'chicken' },
      { e: '🐧', k: 'penguin' }, { e: '🐦', k: 'bird' }, { e: '🦄', k: 'unicorn' }, { e: '🐝', k: 'bee' },
      { e: '🦋', k: 'butterfly' }, { e: '🐌', k: 'snail' }, { e: '🐞', k: 'ladybug' }, { e: '🐢', k: 'turtle' },
      { e: '🐍', k: 'snake' }, { e: '🐙', k: 'octopus' }, { e: '🦀', k: 'crab' }, { e: '🐳', k: 'whale' },
      { e: '🐬', k: 'dolphin' }, { e: '🐟', k: 'fish' }, { e: '🌵', k: 'cactus' }, { e: '🎄', k: 'christmas tree' },
      { e: '🌲', k: 'tree evergreen' }, { e: '🌴', k: 'palm tree' }, { e: '🌱', k: 'seedling sprout' }, { e: '🌿', k: 'herb leaf' },
      { e: '☘️', k: 'shamrock clover' }, { e: '🍀', k: 'four leaf clover luck' }, { e: '🌹', k: 'rose flower' }, { e: '🌺', k: 'hibiscus flower' },
      { e: '🌸', k: 'blossom flower' }, { e: '🌼', k: 'daisy flower' }, { e: '🌻', k: 'sunflower' }, { e: '⭐', k: 'star' },
      { e: '🌟', k: 'glowing star' }, { e: '✨', k: 'sparkles' }, { e: '⚡', k: 'lightning bolt' }, { e: '🔥', k: 'fire lit flame hot' },
      { e: '🌈', k: 'rainbow' }, { e: '☁️', k: 'cloud' }, { e: '💧', k: 'droplet water' }, { e: '🌊', k: 'wave ocean' },
    ],
  },
  {
    id: 'food', icon: 'restaurant', label: 'Food and drink',
    emojis: [
      { e: '🍎', k: 'apple' }, { e: '🍐', k: 'pear' }, { e: '🍊', k: 'orange' }, { e: '🍋', k: 'lemon' },
      { e: '🍌', k: 'banana' }, { e: '🍉', k: 'watermelon' }, { e: '🍇', k: 'grapes' }, { e: '🍓', k: 'strawberry' },
      { e: '🫐', k: 'blueberries' }, { e: '🍒', k: 'cherry' }, { e: '🍑', k: 'peach' }, { e: '🥭', k: 'mango' },
      { e: '🍍', k: 'pineapple' }, { e: '🥥', k: 'coconut' }, { e: '🥝', k: 'kiwi' }, { e: '🍅', k: 'tomato' },
      { e: '🥑', k: 'avocado' }, { e: '🥦', k: 'broccoli' }, { e: '🌽', k: 'corn' }, { e: '🥕', k: 'carrot' },
      { e: '🥐', k: 'croissant' }, { e: '🍞', k: 'bread' }, { e: '🥖', k: 'baguette' }, { e: '🧀', k: 'cheese' },
      { e: '🥚', k: 'egg' }, { e: '🍳', k: 'fried egg cooking' }, { e: '🥓', k: 'bacon' }, { e: '🍔', k: 'burger' },
      { e: '🍟', k: 'fries' }, { e: '🍕', k: 'pizza' }, { e: '🌭', k: 'hot dog' }, { e: '🥪', k: 'sandwich' },
      { e: '🌮', k: 'taco' }, { e: '🌯', k: 'burrito' }, { e: '🍜', k: 'ramen noodles' }, { e: '🍝', k: 'pasta spaghetti' },
      { e: '🍣', k: 'sushi' }, { e: '🍤', k: 'shrimp' }, { e: '🍦', k: 'ice cream' }, { e: '🍩', k: 'donut' },
      { e: '🍪', k: 'cookie' }, { e: '🎂', k: 'cake birthday' }, { e: '🍰', k: 'cake slice' }, { e: '🍫', k: 'chocolate' },
      { e: '🍬', k: 'candy sweet' }, { e: '🍭', k: 'lollipop' }, { e: '☕', k: 'coffee tea' }, { e: '🍵', k: 'tea green' },
      { e: '🥤', k: 'soda drink cup' }, { e: '🍺', k: 'beer' }, { e: '🍻', k: 'beers cheers' }, { e: '🥂', k: 'champagne cheers' },
      { e: '🍷', k: 'wine' }, { e: '🥃', k: 'whiskey' },
    ],
  },
  {
    id: 'travel', icon: 'directions_car', label: 'Travel and places',
    emojis: [
      { e: '🚗', k: 'car' }, { e: '🚕', k: 'taxi' }, { e: '🚙', k: 'suv car' }, { e: '🚌', k: 'bus' },
      { e: '🏎️', k: 'race car fast' }, { e: '🚓', k: 'police car' }, { e: '🚑', k: 'ambulance' }, { e: '🚒', k: 'fire truck' },
      { e: '🚚', k: 'truck delivery' }, { e: '🚛', k: 'lorry truck' }, { e: '🚜', k: 'tractor' }, { e: '🛴', k: 'scooter' },
      { e: '🚲', k: 'bike bicycle' }, { e: '🛵', k: 'moped scooter' }, { e: '🏍️', k: 'motorcycle' }, { e: '✈️', k: 'plane flight travel' },
      { e: '🚀', k: 'rocket launch space' }, { e: '🛸', k: 'ufo' }, { e: '🚁', k: 'helicopter' }, { e: '⛵', k: 'sailboat' },
      { e: '🚤', k: 'speedboat' }, { e: '🚢', k: 'ship cruise' }, { e: '🏠', k: 'house home' }, { e: '🏡', k: 'home garden' },
      { e: '🏢', k: 'office building' }, { e: '🏰', k: 'castle' }, { e: '🗽', k: 'statue liberty' }, { e: '🗼', k: 'tower' },
      { e: '🌉', k: 'bridge night' }, { e: '🎡', k: 'ferris wheel' }, { e: '🎢', k: 'roller coaster' }, { e: '🏖️', k: 'beach' },
      { e: '🏝️', k: 'island' }, { e: '🏔️', k: 'mountain snow' }, { e: '🌋', k: 'volcano' }, { e: '🏕️', k: 'camping tent' },
      { e: '🌅', k: 'sunrise' }, { e: '🌄', k: 'sunrise mountain' }, { e: '🌃', k: 'night city' }, { e: '🌆', k: 'sunset city' },
    ],
  },
  {
    id: 'activities', icon: 'emoji_events', label: 'Activities',
    emojis: [
      { e: '⚽', k: 'soccer football' }, { e: '🏀', k: 'basketball' }, { e: '🏈', k: 'football american' }, { e: '⚾', k: 'baseball' },
      { e: '🎾', k: 'tennis' }, { e: '🏐', k: 'volleyball' }, { e: '🏉', k: 'rugby' }, { e: '🎱', k: 'pool 8 ball' },
      { e: '🏓', k: 'ping pong table tennis' }, { e: '🏸', k: 'badminton' }, { e: '⛳', k: 'golf' }, { e: '🏹', k: 'archery bow' },
      { e: '🎣', k: 'fishing' }, { e: '🥊', k: 'boxing glove' }, { e: '🥋', k: 'martial arts karate' }, { e: '⛸️', k: 'ice skate' },
      { e: '🎿', k: 'ski' }, { e: '🏂', k: 'snowboard' }, { e: '🏆', k: 'trophy win champion' }, { e: '🥇', k: 'gold medal first' },
      { e: '🥈', k: 'silver medal second' }, { e: '🥉', k: 'bronze medal third' }, { e: '🏅', k: 'medal' }, { e: '🎖️', k: 'military medal' },
      { e: '🎯', k: 'target bullseye dart' }, { e: '🎮', k: 'game controller' }, { e: '🎲', k: 'dice' }, { e: '♟️', k: 'chess' },
      { e: '🎭', k: 'theater drama' }, { e: '🎨', k: 'art paint palette' }, { e: '🎤', k: 'mic sing' }, { e: '🎧', k: 'headphones music' },
      { e: '🥁', k: 'drum' }, { e: '🎸', k: 'guitar' }, { e: '🎹', k: 'piano keyboard' }, { e: '🎺', k: 'trumpet' },
      { e: '🎻', k: 'violin' }, { e: '🎬', k: 'movie clapper film' },
    ],
  },
  {
    id: 'objects', icon: 'lightbulb', label: 'Objects',
    emojis: [
      { e: '⌚', k: 'watch time' }, { e: '📱', k: 'phone mobile' }, { e: '💻', k: 'laptop computer' }, { e: '⌨️', k: 'keyboard' },
      { e: '🖥️', k: 'desktop monitor' }, { e: '🖨️', k: 'printer' }, { e: '📷', k: 'camera photo' }, { e: '🎥', k: 'video camera' },
      { e: '📞', k: 'phone call' }, { e: '📺', k: 'tv television' }, { e: '📻', k: 'radio' }, { e: '⏰', k: 'alarm clock' },
      { e: '🔋', k: 'battery' }, { e: '🔌', k: 'plug power' }, { e: '💡', k: 'idea lightbulb' }, { e: '🔦', k: 'flashlight torch' },
      { e: '🕯️', k: 'candle' }, { e: '📕', k: 'book red' }, { e: '📚', k: 'books library' }, { e: '📝', k: 'memo note write' },
      { e: '✏️', k: 'pencil' }, { e: '🖊️', k: 'pen' }, { e: '🖌️', k: 'paintbrush' }, { e: '📌', k: 'pushpin' },
      { e: '📎', k: 'paperclip' }, { e: '✂️', k: 'scissors cut' }, { e: '🔒', k: 'lock secure' }, { e: '🔑', k: 'key' },
      { e: '🔨', k: 'hammer' }, { e: '🔧', k: 'wrench tool fix' }, { e: '⚙️', k: 'gear settings' }, { e: '🧲', k: 'magnet' },
      { e: '💰', k: 'money bag' }, { e: '💵', k: 'dollar cash money' }, { e: '💳', k: 'credit card' }, { e: '💎', k: 'diamond gem' },
      { e: '✉️', k: 'envelope email mail' }, { e: '📧', k: 'email' }, { e: '📨', k: 'incoming mail' }, { e: '📬', k: 'mailbox' },
    ],
  },
  {
    id: 'symbols', icon: 'tag', label: 'Symbols',
    emojis: [
      { e: '❤️', k: 'red heart love' }, { e: '🧡', k: 'orange heart' }, { e: '💛', k: 'yellow heart' }, { e: '💚', k: 'green heart' },
      { e: '💙', k: 'blue heart' }, { e: '💜', k: 'purple heart' }, { e: '🖤', k: 'black heart' }, { e: '🤍', k: 'white heart' },
      { e: '💔', k: 'broken heart' }, { e: '❣️', k: 'heart exclamation' }, { e: '💕', k: 'two hearts' }, { e: '💞', k: 'revolving hearts' },
      { e: '💓', k: 'beating heart' }, { e: '💗', k: 'growing heart' }, { e: '💖', k: 'sparkling heart' }, { e: '💘', k: 'heart arrow cupid' },
      { e: '💝', k: 'heart gift' }, { e: '💯', k: 'hundred 100 perfect' }, { e: '💢', k: 'anger symbol' }, { e: '💥', k: 'collision boom' },
      { e: '💫', k: 'dizzy star' }, { e: '💦', k: 'sweat droplets' }, { e: '💨', k: 'dash wind fast' }, { e: '✅', k: 'check tick done yes' },
      { e: '❌', k: 'cross x no wrong' }, { e: '❓', k: 'question mark' }, { e: '❗', k: 'exclamation' }, { e: '💤', k: 'zzz sleep' },
      { e: '🔔', k: 'bell notification' }, { e: '🎵', k: 'music note' }, { e: '🎶', k: 'music notes' }, { e: '➕', k: 'plus add' },
      { e: '➖', k: 'minus subtract' }, { e: '💲', k: 'dollar sign money' }, { e: '🔴', k: 'red circle' }, { e: '🟠', k: 'orange circle' },
      { e: '🟡', k: 'yellow circle' }, { e: '🟢', k: 'green circle' }, { e: '🔵', k: 'blue circle' }, { e: '🟣', k: 'purple circle' },
      { e: '⚫', k: 'black circle' }, { e: '⚪', k: 'white circle' },
    ],
  },
  {
    id: 'flags', icon: 'flag', label: 'Flags',
    emojis: [
      { e: '🏁', k: 'checkered flag finish' }, { e: '🚩', k: 'red flag' }, { e: '🎌', k: 'crossed flags' }, { e: '🏴', k: 'black flag' },
      { e: '🏳️', k: 'white flag' }, { e: '🏳️‍🌈', k: 'pride rainbow flag' }, { e: '🇺🇸', k: 'usa america flag' }, { e: '🇬🇧', k: 'uk britain flag' },
      { e: '🇨🇦', k: 'canada flag' }, { e: '🇮🇳', k: 'india flag' }, { e: '🇯🇵', k: 'japan flag' }, { e: '🇰🇷', k: 'korea flag' },
      { e: '🇨🇳', k: 'china flag' }, { e: '🇫🇷', k: 'france flag' }, { e: '🇩🇪', k: 'germany flag' }, { e: '🇮🇹', k: 'italy flag' },
      { e: '🇪🇸', k: 'spain flag' }, { e: '🇧🇷', k: 'brazil flag' }, { e: '🇲🇽', k: 'mexico flag' }, { e: '🇦🇺', k: 'australia flag' },
    ],
  },
]
